package com.juananto11.colorquptes

object QuoteGenerator {
    private val quoteList = listOf(
        Quote( "Cuanto más grande es la dificultad, más gloria hay en superarla", "Epícuro" ),
        Quote( "La vida debe ser comprendida hacia atrás. Pero debe ser vivida hacia delante",  "Søren Kierkegaard"),
        Quote( "El hombre está condenado a ser libre",  "Jean-Paul Sartre"),
        Quote( "En todo hay una parte de todo", "Anaxágoras" ),
        Quote( "El hombre valiente es el que no solo supera a sus enemigos, sino también a sus placeres", "Demócrito" ),
        Quote( "La creatividad requiere que la valentía se desprenda de las certezas", "Erich Fromm" ),
        Quote( "Aquellos que no conocen la historia están condenados a repetirla", "Edmund Burke" ),
        Quote( "La mejor parte de la belleza es aquella que ninguna imagen puede expresar", "Francis Bacon" ),
        Quote( "De una pequeña chispa puede prender una llama", "Dante" ),
        Quote( "El entorno da forma a las acciones del individuo", "B. F. Skinner" ),
        Quote( "Nadie puede herirme sin mi permiso", "Gandhi" ),
        Quote( "Puedo controlar mis pasiones y emociones si puedo entender su naturaleza", "Spinoza" ),
        Quote( "Los seres humanos no nacen para siempre el día en que sus madres los alumbran, sino que la vida los obliga a parirse a sí mismos una y otra vez", "Gabriel García Márquez" ),
        Quote( "Ser independiente de la opinión pública es la primera condición formal para lograr algo grande", "Friedrich Hegel" ),
        Quote( "Saber es relativamente fácil. Querer y obrar de acuerdo a lo que uno quisiera, es siempre más duro", "Aldous Huxley" ),
        Quote( "Donde funciona un televisor, seguro que hay alguien que no está leyendo", "John Irving" ),
        Quote( "La juventud es feliz porque tiene la capacidad de ver la belleza. Cualquiera que conserve la capacidad de ver la belleza jamás envejece", "Franz Kafka" ),
        Quote( "El tacto es el arte de dejar ver algo sin hacer un enemigo", "Isaac Newton" ),
        Quote( "Vivimos en el mejor de los posibles mundos", "Leibniz" ),
        Quote( "El que es bueno para poner excusas rara vez es bueno para cualquier otra cosa", "Benjamin Franklin" ),
        Quote( "Aferrarse a la ira es como beber veneno y esperar que la otra persona muera", "Buda" ),
        Quote( "No hay nada como volver a un lugar que permanece sin cambiar para encontrar las formas en las que tu mismo has alterado", "Nelson Mandela" ),
        Quote( "Si no creemos en la libertad de expresión de las personas que despreciamos, no creemos en ella en absoluto", "Noam Chomsky" ),
        Quote( "Lo que logramos internamente cambiará nuestra realidad exterior", "Plutarco" ),
        Quote( "No se desarrolla el coraje al ser feliz en tus relaciones todos los días. Se desarrolla el coraje al sobrevivir tiempos difíciles y desafiando la adversidad", "Epícuro" ),
        Quote( "Nada refuerza tanto la autoridad como el silencio", "Leonardo da Vinci" ),
        Quote( "La cosa más difícil en la vida es conocerte a ti mismo", "Tales" ),
        Quote( "La fundación de todo todo estado es la educación de sus jóvenes", "Diógenes" ),
        Quote( "No es lo que te ocurre, sino cómo reaccionas lo que importa", "Epíteto" ),
        Quote( "Solo hay un camino hacia la felicidad y es cesar de preocuparse por cosas que están fuera del alcance de tu voluntad", "Epíteto" ),
        Quote( "Los grandes resultados requieren grandes ambiciones", "Heráclito" ),
        Quote( "La persona que es una maestra en la paciencia puede con todo lo demás", "George Savile" ),
        Quote( "La esperanza es un buen desayuno, pero una mala cena", "Francis Bacon" ),
        Quote( "Alguien que no cree en los milagros no es realista", "David Ben-Gurión" ),
        Quote( "No hay una visión más triste que la de un joven pesimista", "Mark Twain" ),
        Quote( "El riesgo de una mala decisión es preferible al terror de la indecisión", "Maimónides" ),
        Quote( "La educación es el movimiento de la oscuridad a la luz", "Allan Bloom" ),
        Quote( "Saber que no se sabe, eso es humildad. Pensar que uno sabe lo que no sabe, eso es enfermedad", "Lao-tsé" ),
        Quote( "Al final, no os preguntarán qué habéis sabido, sino qué habéis hecho", "Jean de Gerson" ),
        Quote( "La vida es muy simple, pero insistimos en hacerla complicada", "Confucio" ),
        Quote( "Sacar provecho de un buen consejo exige más sabiduría que darlo", "John Churton Collins" ),
        Quote( "Nuestra vida siempre expresa el resultado de nuestros pensamientos dominantes", "Søren Kierkegaard" ),
        Quote( "Al final, no son los años en nuestra vida lo que cuenta, sino la vida en nuestros años", "Abraham Lincoln" ),
        Quote( "Nada es más nocivo para la creatividad que el furor de la inspiración", "Umberto Eco" ),
        Quote( "El éxito consiste en obtener lo que se desea. La felicidad, en disfrutar lo que se obtiene", "Emerson" ),
        Quote( "Un corazón es una riqueza que no se vende ni se compra, pero que se regala", "Gustave Flaubert" ),
        Quote( "Si exagerásemos nuestras alegrías, como hacemos con nuestras penas, nuestros problemas perderían importancia", "Anatole France" ),
        Quote( "La muerte como final de tiempo que se vive sólo puede causar pavor a quien no sabe llenar el tiempo que le es dado a vivir", "Viktor Frankl" ),
        Quote( "La ciencia moderna aún no ha producido un medicamento tranquilizador tan eficaz como lo son unas pocas palabras bondadosas", "Sigmund Freud" ),
        Quote( "El hombre es la medida de todas las cosas", "Protágoras" ),
        Quote( "La paciencia es amarga, pero su fruto es dulce", "Jean-Jacques Rousseau" ),
        Quote( "Estamos dormidos. Nuestra vida es un sueño. Pero a veces despertamos, solo lo suficiente para saber que estamos soñando", "Ludwig Wittgestein" ),
        Quote( "Cambiad de placeres, pero no cambies de amigos", "Voltaire" ),
        Quote( "Carecer de libros propios es el colmo de la miseria", "Benjamin Franklin" ),
        Quote( "Cásate: si por casualidad das con una buena mujer, serás feliz; si no; te volverás filósofo, lo que siempre es útil para el hombre", "Sócrates" ),
        Quote( "Casi todas las personas viven la vida en una silenciosa desesperación", "Henry David Thoreau" ),
        Quote( "Andaríamos mejor si no fuera porque hemos construido demasiados muros y no suficientes puentes", "D. Pire" ),
        Quote( "Antes de casarme tenía seis teorías sobre el modo de educar a los pequeños. Ahora tengo seis pequeños y ningún teoría", "Lord Rochester" ),
        Quote( "Saber y saberlo demostrar es valer dos veces", "Baltasar Gracián" ),
        Quote( "Anunciad con cien lenguas el mensaje agradable; pero dejad que las malas noticias se revelen por sí solas", "Shakespeare" ),
        Quote( "Daría todo lo que sé, por la mitad de lo que ignoro", "René Descartes" ),
        Quote( "Apocarse es virtud, poder y humildad; dejarse apocar es vileza y delito", "Quevedo" ),
        Quote( "La experiencia es la enfermedad que ofrece el menor peligro de contagio", "Oliverio Girondo" ),
        Quote( "La experiencia no es cuanto se vive sino todo el bien que se aprende", "Jairo Fowbier Pabón" ),
        Quote( "La falla de nuestra época consiste en que sus hombres no quieren ser útiles sino importantes", "Churchill" ),
        Quote( "La falta de inteligencia, la pobreza y la carencia de educación son los tres grandes factores de los crímenes", "Auchner" ),
        Quote( "La falta de la humanidad de la computadora consiste en que una vez se la programa y trabaja adecuadamente su honradez es intachable", "Isaac Asimov" ),
        Quote( "La falsa modestia es la más decente de todas las mentiras", "Chamfort" ),
        Quote( "La fe consiste en creer lo que no vemos, y la recompensa es ver lo que creemos", "San Agustín" ),
        Quote( "El hombre sabio no debe abstenerse de participar en el gobierno del Estado, pues es un delito renunciar a ser útil a los necesitados y un cobardía ceder el paso a los indignos", "Epicteto de Frigia" ),
        Quote( "El gran descubrimiento de mi generación es que los seres humanos pueden alterar sus vidas al alterar sus actitudes mentales", "William James" ),
        Quote( "Tú eres aquello que haces, no aquello que dices que harás", "C.  G. Jung" ),
        Quote( "El corazón humano es un instrumento de muchas cuerdas; el perfecto conocedor de los hombres las sabe hacer vibrar todas, como un buen músico", "Charles Dickens" ),
        Quote( "La mayoría de actos sociales deben ser entendidos en su contexto, ya que pierden significado si son aislados", "Solomon Asch" ),
        Quote( "Si una persona ama solo a una persona y es indiferente ante todos los demás, su amor no es amor, sino apego simbiótico o egoísmo ampliada", "Erich Fromm" ),
        Quote( "Los objetivos transforman un paseo aleatorio en una persecución", "Mihaly Csikszentmihalyi" ),
        Quote( "Un hombre que no se alimenta de sus sueños envejece pronto", "William Shakespeare" ),
        Quote( "Si no recuerdas la más ligera locura en que el amor te hizo caer, no has amado", "William Shakespeare" ),
        Quote( "Cuando el sabio señala la luna, el tonto se fija en el dedo", "Confucio" ),
        Quote( "Un amigo es una persona con la que se puede pensar en voz alta", "Ralph Waldo Emerson" ),
        Quote( "El conocimiento de nadie puede ir más allá de su experiencia", "John Locke" ),
        Quote( "Solo hay un dios, el conocimiento, y un demonio, la ignorancia", "Sócrates" ),
        Quote( "Si dios no existiese, sería necesario inventarlo", "Voltaire" ),
        Quote( "El ocio es la madre de la filosofía", "Thomas Hobbe" ),
        Quote( "Somos lo que hacemos de forma repetida. La excelencia, entonces, no es un acto, sino un hábito", "Aristóteles" ),
        Quote( "Nunca pienses que lo sabes todo. Por muy alto que te valores, ten siempre el coraje de decirte a ti mismo: soy un ignorante", "Ivan Pavlov" ),
        Quote( "Los legisladores necesitan ciertamente una escuela de moral", "Simón Bolívar" ),
        Quote( "Al hombre solo le gusta enumerar sus problemas, no suele calcula su felicidad", "Fyodor Dostoyevsky" ),
        Quote( "La recompensa de una buena acción está en haberla hecho", "Séneca" ),
        Quote( "El propósito de la vida es ser feliz", "Dalai Lama" ),
        Quote( "A donde quiera que vayas, ve con todo tu corazón", "Confucio" ),
        Quote( "Puedo resistirlo todo menos la tentación", "Oscar Wilde" ),
        Quote( "La buena vida es inspirada por el amor y guiada por el conocimiento", "Bertrand Russell" ),
        Quote( "Apuntamos por encima del objetivo para llegar a él", "Ralph Waldo Emerson" ),
        Quote( "El conocimiento te dará poder, pero el carácter te dará respeto", "Bruce Lee" ),
        Quote( "Los amigos muestran su amor en tiempos difíciles, no en la felicidad", "Eurípides" ),
        Quote( "El otoño es una segunda primavera cuando cada hoja es una flor", "Albert Camus" ),
        Quote( "Con cada día llega nueva fuerza y nuevos pensamientos", "Eleanor Roosevelt" ),
        Quote( "El conocimiento habla, pero la sabiduría escucha", "Jimi Hendrix" ),
        Quote( "La sociedad no consiste en individuos, sino que se expresa mediante las interrelaciones", "Karl Marx" )
    )

    fun getQuote () = quoteList.random()
}